# Generated by Django 3.2.3 on 2021-07-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='year',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=150),
        ),
    ]
