# Generated by Django 3.2.3 on 2021-07-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_person_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='year',
            field=models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate', 'Graduate')], default='Graduate', max_length=150),
        ),
    ]
