# Generated by Django 3.2.3 on 2021-07-02 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_person_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('-id', '-dob')},
        ),
    ]
