# Generated by Django 3.2.3 on 2021-07-19 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_auto_20210712_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenship',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
            preserve_default=False,
        ),
    ]
